# GitHub Pages Configuration
title: "Full-Stack Interview Cheat Sheets"
description: "Comprehensive reference materials for technical interviews"
theme: minima

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - BACKEND.md
  - FRONTEND.md
  - WS.md
  - SYSTEM_DESIGN.md

# Markdown settings
markdown: kramdown
highlighter: rouge

# Mobile-friendly settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
